/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Boxs: typeof import('./resources/js/components/Boxs.vue')['default']
    Listing: typeof import('./resources/js/components/Listing.vue')['default']
    Pagination: typeof import('./resources/js/components/Pagination.vue')['default']
  }
}
